# Supplier.create(name: "PetKo", email: "petko@gmail.com", phone_number: "123-4567")
# Supplier.create(name: "Cat Goodies Express", email: "catgoodies@gmail.com", phone_number: "232-4321")
# Supplier.create(name:"CatsMart", email: "catsmart@gmail.com", phone_number: "665-CATS")

# Product.create(name: "Cat Collar", price: 5, description: "a handsome bowtie", inventory: 3, supplier_id: 3)
# Product.create(name: "Cat Tree", price: 45, description: "big cat tree", inventory: 1, supplier_id: 3)
# Product.create(name: "Mouse Toy", price: 2, description: "a cute mouse for your cat to kill", inventory: 2, supplier_id: 2)
# Product.create(name: "Cat Bed", price: 10,  description: "a cozy bed for your highness to lay on", inventory: 1, supplier_id: 3)
# Product.create(name: "Cat Bowl", price: 12, description: "the perfect cat bowl for his/her highness to eat from", inventory: 1, supplier_id: 3)
# Product.create(name: "Lion Costume", price: 30, description: "your kitty transforms into a mighty lion", inventory: 1, supplier_id: 2)
# Product.create(name: "All You Need is Love Poster", price: 7, description: "a poster for you to admire cats", inventory: 1, supplier_id: 1)
# Product.create(name: "Cat Hammock", price: 30, description: "what more can you buy your kitty", inventory: 1, supplier_id: 3)

# Image.create(url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-n3dxvQvn0elJFFeFH1G_aYIixmQ9dKRZww&usqp=CAU", product_id: 1)
# Image.create(url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROP1EaOtuKQL-Zk4uDCpM5f_v9Ndt1mhAs2A&usqp=CAU", product_id: 2)
# Image.create(url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTppC4PB39oAudYajxjSw4BwB0i3MRJmFoGWw&usqp=CAU", product_id: 3)
# Image.create(url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBkKd-wmNSHQ4Nhoeu4dtI11Y7BrxH85UHpQ&usqp=CAU", product_id: 4)
# Image.create(url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBrSnxjxbtrbk019uXoaNwFI_icREF8tfwGQ&usqp=CAU", product_id: 6)
# Image.create(url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8NObTl4YCJMCr1tigkj2bKpHE5iehiEdU1w&usqp=CAU", product_id: 7)
# Image.create(url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB5mJ0U81t7F3GUX6h103p2xtfGlztwMi31Q&usqp=CAU", product_id: 8)
# Image.create(url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTRPqPj-So_qOxU39y_qCiFS6MOMkGp0Z-oA&usqp=CAU", product_id: 9)

# Category.create(name: "Toys")
# Category.create(name: "Collars and Bowls")
# Category.create(name: "Beds and Lounges")

ProductCategory.create(category_id: 1, product_id: 2)
ProductCategory.create(category_id: 1, product_id: 3)
ProductCategory.create(category_id: 1, product_id: 7)
ProductCategory.create(category_id: 1, product_id: 8)
ProductCategory.create(category_id: 2, product_id: 1)
ProductCategory.create(category_id: 2, product_id: 6)
ProductCategory.create(category_id: 3, product_id: 2)
ProductCategory.create(category_id: 3, product_id: 4)
ProductCategory.create(category_id: 3, product_id: 9)


